services:
  localstack:
    container_name: localstack-poc
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/var/lib/localstack
